### ISSUE TITLE
Question: How exactly does --window work?

### ISSUE THREAD

**Issue by alexbepple** [jeffbski/wait-on#14]
From some cursory testing my impression is that the time required by wait-on, when successful, is roughly 0.5 s + 2 * window.

E.g.:
$ wait-on --config wait-on.json --window 300 --timeout 5000 http://localhost:3000
Done in 1.12s.
$ wait-on --config wait-on.json --window 1000 --timeout 5000 http://localhost:3000
Done in 2.56s.
$ wait-on --config wait-on.json --window 2000 --timeout 5000 http://localhost:3000
Done in 4.54s.

But from the description, I rather thought that "--window" would be roughly the total time required by wait-on, when successful.

Could you kindly explain precisely how "--window" works?

**Comment by jeffbski** [comment]
@alexbepple Thanks for writing, I'm sorry for the confusion. I'll have to see if I can figure out how to improve the docs for that feature.

Basically window is the stability window of time that things have been available and not changed. 

So internally things kick off after the initial `delay`, then check frequency are made based on the value for `interval`.

The `window` determines how often to check the stability of everything.

In the case of a build system that is writing to files, the file might exist but it is still being written to, so we don't want to signal success until we have waited enough time to feel good that it has finished being written to. This is what the `window` stability configuration is supposed to achieve. Similarly when checking ports we simply check that they stay available the entire time before considering them good (since they don't have a size that can vary).

So internally the observable groups events into windows of time and I check that things have stayed available and not changed size in the window so I can signal a success. If anything changed or became not available then we reset the window and continue waiting.

Depending on how quickly your resources stabilize, it could take `2*window + delay` to see that things have stabilized. In the ideal case it could be as low as `window + delay`, but it really depends on how fast things come up and where they fall in the delay, iteration, and window boundaries.

Hopefully that helps?
