### ISSUE TITLE
Waiting on an https resource that uses self-signed certs

### ISSUE THREAD

**Issue by lumberj** [jeffbski/wait-on#2]

**Comment by lumberj** [comment]
Workaround is to set `NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by jeffbski** [comment]
If we want this to work from the command line then it feels like it might be better to just use the `NODE_TLS_REJECT_UNAUTHORIZED=0` approach. It is less to setup and I don't really think that it compromises anything, we are just checking for availability. Anything using the service can still choose to strict validate their ssl connection when they connect.

Let me know if you agree or I am missing something important.

I like the work you did for the pull request, would you be willing to provide an alternative one using `NODE_TLS_REJECT_UNAUTHORIZED=0`?

**Comment by lumberj** [comment]
> I like the work you did for the pull request, would you be willing to provide an alternative one using NODE_TLS_REJECT_UNAUTHORIZED=0?

Not sure what you mean?

**Comment by jeffbski** [comment]
If you agree that going with the NODE_TLS_REJECT_UNAUTHORIZED=0 approach (for the reasons I mentioned) rather than adding all of the other config like your original pull request did, then would you be willing to make a different pull request that just makes this change to the code setting this flag in the https call NODE_TLS_REJECT_UNAUTHORIZED=0, then I'll merge that PR instead.

It's a simple change so I figured it would be pretty easy. Since it was your idea, it would be great to merge your PR for that, then you would have the credit in the code for the change.

Hopefully that makes sense. I was just saying that if we make this simple change then it should work well from the command line in addition to programmatically and in either case it is simpler to configure (basically nothing additional needs to be setup to use).

If we need to add the other config for other reasons then we can, but I'm thinking maybe they aren't necessary if we have the NODE_TLS_REJECT_UNAUTHORIZED=0, would you agree?

**Comment by lumberj** [comment]
Sorry, I misspoke.

`NODE_TLS_REJECT_UNAUTHORIZED` is an environmental variable that can be set in node to ignore invalid TLS server certificates. This is helpful if you're testing a client and server, and using self-signed certificates for the server. This works as is. There is no reason to add a PR for this, as the module should not be modifying the environment.

I will close this PR, because this technically addresses that. There is still another open issue, which is that HTTP authentication is not supported. #3 addresses by that allow a user to pass options for basic-auth, http-signature, or tls-client certificates.

**Comment by lumberj** [comment]
Closed in favor of #4

**Comment by jeffbski** [comment]
ok, thanks for the clarification, I was thinking that was an https option not an environment variable and thus the confusion. I guess the way to do it with an https option is setting rejectUnauthorized to false and passing in a custom agent. 

I'll merge #3 now and then I can figure out later how the options could be used from the command line, maybe one would supply a js or json config.
