### ISSUE TITLE
Bug: wait-on can't recognize project, that was built and started using command ng serve

### ISSUE THREAD

**Issue by YevheniiaMazur** [jeffbski/wait-on#23]
### Steps to reproduce
- Create empty angular project using command `ng new projName`
- Switch to new project directory
- Install in empty proj wait-on package using command `npm install wait-on --save-dev`
- Install all needed modules using command `npm install`
- Build and start app using command `ng serve`
- In separate tab enter command `$(npm bin)/wait-on -v http://localhost:4200/#/ && npm run e2e` (flag -v is needed for displaying response logs)

### Actual result
wait-on script returns child next [ { 'http://localhost:4200/#/': -404 } ] even if app is successfully started
![actualresult](https://user-images.githubusercontent.com/27342505/37469331-b0d3b550-286d-11e8-887c-10562708c787.jpg)

### Expected result
wait-on script behaves in the same way for all types of app starting

**Comment by jeffbski** [comment]
@YevheniiaMazur thanks for reporting this. I'll see if I can reproduce this using the steps you outline. 

One thought I have from your instructions. If you are going to run a command with a # in it, then you need to put that into quotes otherwise bash will consider the rest of the command a comment.

```
$(npm bin)/wait-on -v "http://localhost:4200/#/" && npm run e2e
```

From the screenshot it looks as though you didn't have the # in the command so I'm guessing this was not the actual problem. 

I'll see if I can figure out what is going on.

**Comment by jeffbski** [comment]
@YevheniiaMazur It turns out that ng serve does not implement HEAD http method so that's why it is coming back as 404. 

If you want to use a GET method then just change your command to 

`wait-on -v http-get://localhost:4200/ && npm run e2e`

Using the `http` prefix makes wait-on issue a HEAD request and using the `http-get` makes it use a GET request.

Hopefully if you change to `http-get` that should fix your problem. Also quote the whole string if you use # in the URL.

**Comment by YevheniiaMazur** [comment]
@jeffbski , thank you for this great workaround. I tried `wait-on -v http-get://localhost:4200/ && npm run e2e` and it works
