### ISSUE TITLE
Feature suggestion: trigger even if GET returns 4XX or 5XX codes

### ISSUE THREAD

**Issue by olekon** [jeffbski/wait-on#45]
Sometimes 3rd party service may be used with wait-on. and we can't guarantee that it will return 2XX codes on GET or HEAD. For example it allows only POST requests and returns 400 code on GET or HEAD

Is it possible to add an option to allow wait-on trigger upon receiving any code? Receiving code by itself means that server is up.

**Comment by MikeWeiZhou** [comment]
I would also love this feature.

Use case:
API server requires authentication to get a 2XX response status code, but I got back 5XX (e.g. forbidden).

Having any response means the resource is up, and it makes no sense for me to pass in authentication details to poll to see if a server is up or not.

**Comment by HcySunYang** [comment]
Yes, I also want this feature.
I use this library in E2E testing and I start a server, but this server always returns 500 status code (this is as expected because I want to test custom error page functionality).
Thanks for your work.

**Comment by jeffbski** [comment]
In order to provide the most flexibility without complicating the API, how about if we allow this as part of a config file. 

In wait-on v5, the http client Axios allows this via an optional validateStatus function so I could easily allow that to be passed in. If you wanted to allow 401's in addition to 200's then it would look like this.

```js
module.exports = {
  // `validateStatus` defines whether to resolve or reject the promise for a given
  // HTTP response status code. If `validateStatus` returns `true` (or is set to `null`
  // or `undefined`), the promise will be resolved; otherwise, the promise will be
  // rejected. Default is status >= 200 && status < 300.
  validateStatus: function (status) {
    return status == 401 || (status >= 200 && status < 300); 
  },
};
```

and obviously you could adjust to allow any status if that's what you want. 

Would this be acceptable?

**Comment by jeffbski** [comment]
I have added validateStatus to v5.0.0 and published it. You should be able to accomplish what you wanted.
