### ISSUE TITLE
reverse wait support

### ISSUE THREAD

**Issue by skarbovskiy** [jeffbski/wait-on#5]
Thanks for this great module. One thing that really lacks here is reverse wait support.

For example: one wants his script to wait until another service is down (provisioning, monitoring etc needs).

How are you looking at this kind of functionality? Generally I can contribute this as a PR if you don't mind.

**Comment by jeffbski** [comment]
That's a use case I hadn't considered but I can see how it would be useful.
Would it be sufficient to just invert the check with a flag or do you think
there would be a situation where one needs to wait for some to go down and
others to come up?

Maybe the latter case would just be handled by running two instances.

Adding a flag to invert the check should be simple.

I love PR's so that would be great.

Let me know what you think.

Jeff

On Wednesday, April 6, 2016, skarbovskiy <notifications@github.com> wrote:

> Thanks for this great module. One thing that really lacks here is reverse
> wait support.
>
> For example: one wants his script to wait until another service is down
> (provisioning, monitoring etc needs).
>
> How are you looking at this kind of functionality? Generally I can
> contribute this as a PR if you don't mind.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffbski/wait-on/issues/5>
>


-- 
Jeff Barczewski
Founder of CodeWinds
http://codewinds.com/
Web developer training - screencasts, podcast, blog

**Comment by skarbovskiy** [comment]
yeah, i think flag would be great. if we need up and down check we can run multiple `wait-on` commands. I'll provide PR soon.
