### ISSUE TITLE
Different behavior from 4.0.0 to 5.0.0 - jest/jsdom logging errors to console

### ISSUE THREAD

**Issue by filipedeschamps** [jeffbski/wait-on#64]
For some reason, after upgrading from `4.0.0` to `5.0.0` I started to receive these errors. Everything works as expected, but it started to log an error every time it tries to check if the service is available... and until it isn't, it logs this error.

The `verbose` is in default `false`.

```
      Error: Error: connect ECONNREFUSED 127.0.0.1:3000
          at Object.dispatchError (/Users/filipedeschamps/local/coding/BrasilAPI/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
          at Request.<anonymous> (/Users/filipedeschamps/local/coding/BrasilAPI/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
          at Request.emit (events.js:327:22)
          at Request.onRequestError (/Users/filipedeschamps/local/coding/BrasilAPI/node_modules/request/request.js:877:8)
          at ClientRequest.emit (events.js:315:20)
          at Socket.socketErrorListener (_http_client.js:461:9)
          at Socket.emit (events.js:315:20)
          at emitErrorNT (internal/streams/destroy.js:96:8)
          at emitErrorCloseNT (internal/streams/destroy.js:68:3)
          at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined
```

Is there something I can do about it? Thanks in advance!

**Comment by jeffbski** [comment]
That's strange. Are you using wait-on CLI or the API?

**Comment by filipedeschamps** [comment]
Hi @jeffbski I'm using the API, here: https://github.com/filipedeschamps/BrasilAPI/blob/master/tests/helpers/server.js

I didn't change anything between v4 to v5 and it's very easy to replicate actually. Just need to download the repo, install dependencies (wait-on v4 or v5), and run `npm test`.

In v4 no log will appear, and v5 will 👍

**Comment by jeffbski** [comment]
ok, I'll see if I can track it down. Maybe something due to one of the new dependencies. I'll see if I can figure it out and let you know. Thanks for reporting it.

**Comment by jeffbski** [comment]
@filipedeschamps after not being able to reproduce this in my code, I pulled down your repo and ran like you suggested.

Apparently this is caused by something that the jest jsdom is mocking or hooking into so that it has access to request errors. So this is not actually coming from wait-on but from the jsdom virtual-console code. I assume the reason you didn't get the error before was due to the fact that the older wait-on used a different http client which jsdom was not messing with.

One way to not have jsdom messing with things is to tell jest that your test environment is node, so it doesn't think it is working in a browser environment.

So if you change your jest.config.js to this

```js
module.exports = {
  testEnvironment: 'node', // this line disables the jsdom hooks
  testTimeout: 30000,
};
```

then it won't be hooking into the http client and logging these errors. You might see things running faster as well since you don't need this overhead.

There might be other ways to silence this error but it would take more investigation or asking the jest/jsdom team. They really shouldn't be just logging things blindly like this IMO. 

Also note that your test suites are using the same port for both suites and since jest runs suites in parallel I was having sporadic race condition failures in your tests, sometimes they all pass, sometimes the second suite fails.

So you can either use a different port for each suite so they don't interfere with each other thus being able to run these in parallel or add the --runInBand to your jest command so it will run the suites in serial. After doing the latter, the tests were always successful.

**Comment by jeffbski** [comment]
Kevin Simper wrote a blog article discussing this jsdom behavior and how to disable it. 

https://medium.com/@kevinsimper/how-to-disable-jsdom-in-jest-make-jest-run-twice-as-fast-a01193f23405

**Comment by jeffbski** [comment]
@filipedeschamps I found a way to force the httpClient (axios) that wait-on uses to use the node.js http adapter not the browser xhr adapter. Basically since jest has jsdom turned on by default, it polyfills in xhr which normally wouldn't be available and axios detects that and uses that for its connection otherwise it would have used the node.js http. With this change I can force it to always use the node.js http adapter and thus you won't need to specify testEnvironment: 'node'.

**Comment by jeffbski** [comment]
@filipedeschamps I have made the changes and they have landed in wait-on@5.0.1

https://github.com/jeffbski/wait-on/releases/tag/v5.0.1

So this should fix the logging issue that jest/jsdom was causing by having polyfilled xhr. You won't need to specify jest testEnvironment: 'node' but your logs will remain clean of wait-on request errors. (you can of course still use testEnvironment: 'node' if you want, just not forced to).

Also don't forget to update your repo to use unique ports for your test suites or to use the `--runInBand` jest CLI option.

**Comment by filipedeschamps** [comment]
You are awesome @jeffbski 😍 

Thank you very much!! 👍👍👍👍👍

**Comment by jeffbski** [comment]
You are welcome. Glad we were able to figure out a solution. Thanks for your help in reporting it and working with me. @filipedeschamps
